function [ G ] = G_function( S, p, c, A, N_c,...
                             K_rw_i, K_rw_d, K_rn_i, K_rn_d,...
                             Pb_i, Pb_d, S_wr_i, S_wr_d, S_nr_i, S_nr_d,...
                             alpha_i, alpha_d, beta_i, beta_d, gamma_i, gamma_d,...
                             mu_w, mu_n )


 h_hyst = h_hysteresis( S, p, K_rw_i, K_rw_d, K_rn_i, K_rn_d,...
                        Pb_i, Pb_d, S_wr_i, S_wr_d, S_nr_i, S_nr_d,...
                        alpha_i, alpha_d, beta_i, beta_d, gamma_i, gamma_d,...
                        mu_w, mu_n );
                    
 f_hyst = f_hysteresis( S, p, K_rw_i, K_rw_d, K_rn_i, K_rn_d,...
                        Pb_i, Pb_d, S_wr_i, S_wr_d, S_nr_i, S_nr_d,...
                        alpha_i, alpha_d, beta_i, beta_d, gamma_i, gamma_d,...
                        mu_w, mu_n );            
     
 G = (1./(N_c*h_hyst)).*(A-c*S+f_hyst);


end

