function [ rhs_ode ] = Rhs_ODE( t, y, c, A, N_c,...
                                K_rw_i, K_rw_d, K_rn_i, K_rn_d,...
                                Pb_i, Pb_d, S_wr_i, S_wr_d, S_nr_i, S_nr_d,...
                                alpha_i, alpha_d, beta_i, beta_d, gamma_i, gamma_d,...
                                mu_w, mu_n, epsilon )

h_hyst = h_hysteresis( y(1), y(2), K_rw_i, K_rw_d, K_rn_i, K_rn_d,...
                       Pb_i, Pb_d, S_wr_i, S_wr_d, S_nr_i, S_nr_d,...
                       alpha_i, alpha_d, beta_i, beta_d, gamma_i, gamma_d,...
                       mu_w, mu_n );

f_hyst = f_hysteresis( y(1), y(2), K_rw_i, K_rw_d, K_rn_i, K_rn_d,...
                       Pb_i, Pb_d, S_wr_i, S_wr_d, S_nr_i, S_nr_d,...
                       alpha_i, alpha_d, beta_i, beta_d, gamma_i, gamma_d,...
                       mu_w, mu_n );
                   
[ pc_p, pc_m ] = Pc_pm( y(1), Pb_i, Pb_d, S_wr_i, S_wr_d,...
                        S_nr_i, S_nr_d, gamma_i, gamma_d );
                     
rhs_ode = zeros(2,1);

t

rhs_ode(1) = Psi( (pc_p-y(2))./pc_m, epsilon )/c;
rhs_ode(2) = (1./(N_c*h_hyst)).*(A-c*y(1)+f_hyst);

end

